version: '3.9'

services:
  api:
    container_name: stockcontrol-api
    build: 
      context: ./server
    ports:
      - "8080:8080"
    
  web:
    container_name: stockcontrol-web
    build: 
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - POSTGRES_DB=stock_control
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin